language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: mjMzwyQcw8A2gk1WlLtLWFiQRrfbSEAJKDt/s41/iHi37wu1z0bklInUCGk8nbH0HlKk+smc28X9hYKFmSLBAuIcSdFeOil0x4BOJaDYDhDrv3tgU1oFDAohpS+Yusj/YUogPiCsWgfnfhtolgOemFYpCNjPPnQ9HT8MWevnuTvinz1d/TLfoiQXRy1G86dV2oVtLsc7UmHdabyV1PahmT45b5MczMUktzL6PWFh73swy6q3vdu+KEp11wPJa6Ptn6yS/fc0dTi81Gb/ZcX2aI9ZiL5yRkZyxXcSMLDUMoxhTZ0XaVALG35akBV7xGZjJSU+NdU9x4XnF3wVGpIBvgv5ZLY+nDyTtEO0DWJyXk+FHQSuJf5brctZyT12mU8u5Uv0g/7tYhoG6t1adOTQrhqqo54VVqEpUPMZGR+z9wIGUMrnDFlgENw7kg5zRpMspeOeZ+uda630bhFsWNyQG0gCk9mzLxZq+aX8dvXC3zhD4RyuKhATUHi9ZpMOmVoIpRV0cEIXRduOJmeInc2lWc6oOCUMQqTL5oHGZbUacip7SFzl0qSJiLnDTDJX2DnOoZVNYN9IOl8y4nIRg4XOdeJekPth81753KcCMiOHD6WJytka7cV/tRzf3k/U47MXUPieHwvSf0XMAoE9Y7sEvIAAYtAxWSdkiQS8U9ABlt4=
